# --- File: agents/urls.py ---
# URL configuration for the agents app.
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AgentViewSet

router = DefaultRouter()
router.register(r'agents', AgentViewSet, basename='agent') # Register AgentViewSet under '/api/agents'

urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
]

